### ISSUE TITLE
integer truncation

### ISSUE THREAD

**Issue by rbw42** [matt-dale/rf-explorer-python-api#2]
Hi again Matt,

I've just started using your tool again thanks. One of the small changes that I made while mucking around with this last year was to fix the integer rounding that converts the text to a number. The existing line:
i = (int(i)/2)*-1#convert to dBm
unnecessarily does integer division, rather than dividing by 2.0 which will keep the extra 0.5 dB accuracy that is displayed on the unit screen. So change it to:
i = int(i)/-2.0  #convert to dBm
There seem to be some weird issues reconnecting on linux machines that I'll try to track down, but this is low-hanging fruit for now.

Cheers,
Randall

**Comment by matt-dale** [comment]
Thank you very much for that. I am uploading a new version of the RFExplorer.py that I re-wrote in order to make everything more accurate.  It will be called RFExplorerV2.py. 

Other than this inherent inaccuracy, there was another severe one that miscalculated the frequency values essentially giving incorrect data.  Two weeks ago I started on this project again. I would appreciate any feedback regarding the new version.  In my simple tests here on a Windows machine, the new module provides much more accurate readings.
